### ISSUE TITLE
Podemos hacer un template?

### ISSUE THREAD

**Issue by ibartomeus** [ecoinfAEET/fact_sheets_aeet#1]
Para hacer fact sheets de cualquier tema, podemos hacer un template wue lea el texto, de por ejemplo un Gdocs? Alguien se anima?

**Comment by ajpelu** [comment]
Hola @ibartomeus. Quizá se pueda hacer un shiny sencillo que lea el texto y lo convierta a md o similar. Mira este ejemplo https://www.showmeshiny.com/try-markdown/

**Comment by ibartomeus** [comment]
Mola, pero creo que voy a ir a lo fácil.  Un shiny esta por encima de mis posibiidades, y no se va a usar tantas veces. Gracias.

**Comment by Pakillo** [comment]
Con [googledrive](http://googledrive.tidyverse.org/) se podría leer un GDocs y después transformar en Rmd (hay varios tools en github para ello). 

Pero habría que partir de un GDocs fijo como plantilla. Si no iba a ser difícil saber dónde colocar cada parte del GDoc en secciones del Rmd

Conclusión: Siempre se podrá intentar automatiza la conversión con scripts, pero en mi opinión lo más sencillo puede ser que la gente prepare un GDoc y luego meterlo todo "a mano" en un Rmd preformateado. Sobre todo teniendo en cuenta que no se va a producir un fact-sheet al día... Ese copy-paste no debería llevar más de 2 minutos, y automaticamente tendríamos fact sheet con el formato deseado.  

(NB: creo que es la primera vez en años que recomiendo hacer algo a mano... :s

**Comment by ibartomeus** [comment]
ok! he creado un template y cierro el issue!
